### ISSUE TITLE
WARNING in Empty property 'box-shadow' at 5844:4. Ignoring.

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#421] opened 2018-11-05 14:14 UTC
## I'm submitting a...

* Bug report 

## Current behavior
Using the latest Default theme 2.59.0 for an Angular 7 application causes the following warning messages, when building for production the application:

WARNING in Empty property 'box-shadow' at 5844:4. Ignoring.
WARNING in Empty property 'box-shadow' at 11952:2. Ignoring.

## Minimal reproduction of the problem with instructions

Use Angular CLI 7 to create a start-up project. Install the latest Default theme 2.59.0 and run ng build --prod.

## Environment
Product:

* Kendo Ui for Angular

Package versions:
 @progress/kendo-theme-default: 2.59.0

**Comment by jberrydev** [comment] 2018-11-15 00:15
I am also seeing this issue.  Looks like it started in version "@progress/kendo-theme-default": "2.57.1". I hard versioned to 2.57.0 and that fixes it.  This is breaking my gulp-sass build  `Error: style declaration must contain a value  box-shadow:;`

**Comment by JoomFX** [comment] 2019-10-04 08:31
Unable to reproduce with 2.61.0+

Introduced with or before 7a543d38e28f542cf5607f9a367e4e0c8016c28b and fixed by or before 13c6198a70148457d1b2dc6bce0bf9078a2774b8

**Closed by JoomFX** 2019-10-04 08:31 UTC
Labels: T:Default, bug
