### ISSUE TITLE
Column name is behind the icon when dragging a column in IE 11

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#657] opened 2019-03-12 14:41 UTC
## I'm submitting a...
* Bug report 

## Current behavior
* In IE 11, the name of the column is behind the icon, when the column is collapsed and trying to reorder it.

## Expected behavior
* The name of the column should be on the right side of the icon.
![Issue 2](https://user-images.githubusercontent.com/33104481/54208617-e9f6ab00-44e4-11e9-99be-36c1828c38d5.png)

## Minimal reproduction of the problem with instructions
Check the link: https://stackblitz.com/edit/angular-qpuo8h-k6njkt?file=app/app.component.ts
![Issue](https://user-images.githubusercontent.com/33104481/54208161-1bbb4200-44e4-11e9-97c5-0ac7fb04c654.png)

## Environment
Product:
* Kendo Ui for Angular

Browser:
- IE version 11

**Comment by PreslavKozovski** [comment] 2019-10-31 14:19
Duplicate of #386

**Closed by PreslavKozovski** 2019-10-31 14:19 UTC
Labels: T:Default, bug
