### ISSUE TITLE
while compiling Kendo-theme-bootstrap 4.43.0 version, I get issue $color: null is not a color.

### ISSUE THREAD

**Issue by Xylontech** [telerik/kendo-themes#3260] opened 2022-01-19 08:45 UTC
**Describe the bug**
while compiling Kendo-theme-bootstrap 4.43.0 version from sass or node-sass, I get error message "$color: null is not a color".

**To reproduce**
Compiling scss file through sass node-sass on cmd

**Expected behavior**
Need to compile the Kendo-theme-bootstrap 4.43.0

**Screenshots**
![compiling issue](https://user-images.githubusercontent.com/98016311/150094864-7c2b519f-ddd5-40ed-b750-ac9860981f18.PNG)

**Affected package (please remove the unneeded items)**
theme-default
theme-bootstrap

**Affected suites (please remove the unneeded items)**
Kendo UI for React

**Affected browsers (please remove the unneeded items)**
Not Applicable

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Add any other context about the bug.

**Comment by joneff** [comment] 2022-01-19 08:59
As a side note, you are compiling with dart-sass, not node-sass (as visible in the message).

Now regarding the problem ... I am not quite sure what the issue is without seeing the content of `scss/vendor/kendo-theme-bootstrap.scss`. Can you paste it here? I am guessing (and that's just a guess) that a variable is missbehaving.

**Comment by Xylontech** [comment] 2022-01-19 09:12
@import "../../node_modules/@progress/kendo-theme-bootstrap/modules/bootstrap/scss/functions";
@import "bootstrap_variables"; (Customize file)
@import "../../node_modules/@progress/kendo-theme-bootstrap/modules/bootstrap/scss/bootstrap";
@import "kendo_variables";  (Customize file)
@import "../custom/custom-variables";  (Customize file)
@import "../../node_modules/@progress/kendo-theme-bootstrap/scss/all";

**Comment by Xylontech** [comment] 2022-01-19 10:44
@import "../../node_modules/bootstrap/scss/functions";
@import "../../node_modules/bootstrap/scss/bootstrap";
@import "../../node_modules/@progress/kendo-theme-bootstrap/scss/all";

On package.json
    "@progress/kendo-theme-bootstrap": "^4.43.0",
    "@progress/kendo-theme-default": "^4.43.0",
    "@progress/kendo-ui": "^2021.3.1207",
    
    Still I got the issue even I remove all the customise variables

**Comment by joneff** [comment] 2022-01-19 11:50
I will need the content of the following three files

* `@import "bootstrap_variables";` (Customize file)
* `@import "kendo_variables";` (Customize file)
* `@import "../custom/custom-variables";` (Customize file)

Our own file should work correctly when compiled on it's own. When I see the content of the above files I will see if any of them may conflict.

**Comment by Xylontech** [comment] 2022-01-19 14:13
@joneff I have remove that customize files.

I try to compile both get the same issue but if I try one by one below list it compile.
@import "../../node_modules/@progress/kendo-theme-bootstrap/modules/bootstrap/scss/bootstrap.scss";
@import "../../node_modules/@progress/kendo-theme-bootstrap/scss/all";

Thank you

**Comment by meriturva** [comment] 2022-01-21 11:50
I have two different projects with the same error, one using bootstrap 4 another one with bootstrap 5.

Do you need a repo or will it be fixed soon?

**Comment by eluchsinger** [comment] 2022-01-21 14:19
Same issue here when updating from 4.42 to 4.43

**Comment by Xylontech** [comment] 2022-01-21 14:45
I need to update all the variable of both bootstrap and kendo which solve the issue. But I don't want to use bootstrap 5 as I have theme the app according to bootstrap 4 which doesn't solve the issue, is there any other way to update only kendo but not bootstrap?

**Comment by icebits** [comment] 2022-01-22 07:37
I am using Visual Studio 2022, with Web compiler 2022+ (node sass), bootstrap 5.1.1 sass, kendo default theme 5.0.1, kendo bootstrap theme 5.0.1 also having this Error: $color2: null is not a color. @return mix( $base, $color, $level );

Using the following sequence, I manage to get rid of the errors.

// Override bootstrap variables here
@import "_bootstrap-overrides.scss";

$custom-colors: ( 
    "yellow": $yellow,
);

@import "../lib/progress/kendo-theme-bootstrap/scss/core/functions/_index.scss";
@import "../lib/progress/kendo-theme-bootstrap/scss/_bootstrap-overrides.scss";
@import "../lib/bootstrap/scss/_functions.scss";
@import "../lib/bootstrap/scss/_variables.scss";
@import "../lib/bootstrap/scss/_mixins.scss";

// Override kendo variables here
$theme-colors: map-merge-multiple($theme-colors, $custom-colors);
$font-family: Arial;
...
...

**Comment by WayneHiller** [comment] 2022-01-24 14:07
I have narrowed it down to @progess\kendo-theme-bootstrap\scss\chip\_variables.scss

![image](https://user-images.githubusercontent.com/1186731/150797571-d9c706f2-6343-46df-b6ae-aba92ccc205c.png)

if I change error to danger above she compiles without errors

**Comment by KimBum** [comment] 2022-07-22 11:24
I am facing the same issue with $tertiary in buttons theme. Tracked it down to the fact that in bootstrap 4 everyone was using the following syntax to default/merge the theme colors together.
```
$theme-colors: () !default;
$theme-colors: map-merge(
  (
    "primary":    $primary,
    "secondary":  $secondary,
    "success":    $success,
    "info":       $info,
    "warning":    $warning,
    "danger":     $danger,
    "light":      $light,
    "dark":       $dark
  ),
  $theme-colors
);
```

This has now become the following in both bootstraps variables and kendo theme variables:
```
$theme-colors: (
  "primary":    $primary,
  "secondary":  $secondary,
  "success":    $success,
  "info":       $info,
  "warning":    $warning,
  "danger":     $danger,
  "light":      $light,
  "dark":       $dark
  ) !default;
```
Meaning the whole map would be defaulted. Since like @WayneHiller mentioned there is a discrepancy between `danger` and `error` withing the map definitions of kendo and bootstrap and they no longer get merged as they did before. There will likely always be an issue with it.
Bootstrap themselves are not accessing these colors via `map-get`, because they assume the map might look drastically different. This does not seem to be the case with Kendo. That does in fact mean that the order of imports suggested by Kendos documentation works to solve this issue, but only as long as the user has not defined `$theme-colors` beforehand, as your documentation suggest it should be done. The suggested import order would also result in `$danger` color key being removed from the map and as such bootstraps generated utilities.

### Thoughts
In their [customization guide to maps](https://getbootstrap.com/docs/5.2/customize/sass/#maps-and-loops) Bootstrap describes to use map-merge to add values to the list **after** importing the bootstrap file, which has the map defined. Since kendo does not do this at the current point in time (and judging from release list there will probably not be a patch release for 4.44) and I also want to extend the list from our end, I need a workaround to get all three maps together again without losing the respective variable information on each level.

As soon as I figure this out, I would post our solution here 🙂

**Comment by joneff** [comment] 2022-08-26 16:25
This is going to be a lengthy reply, trying to address all questions raised, so please bear with me. But first, some context:

**Kendo UI, kendo themes, Bootstrap and kendo-theme-bootstrap**

The idea behind the theme was, as naive as it may be, to have a theme for Kendo UI that is easily customizable by Bootstrap variables. I say "naive" because there is a big difference between what Bootstrap provide as guidelines for ... let's call them components, and what we actually have in Kendo UI.

It's a lot like "fill in the gaps" or solving a sudoku with 4 squares filled: it's not impossible, but there is more than one way to do things.

For some time that "fill in the gaps" and "use Bootstrap variables" wasn't really a problem, until the first actual sass version came to be and it turned out that the secondary [button](https://getbootstrap.com/docs/4.0/components/buttons/) of bootstrap is a bit dark. Why was that an issue? Well imagine every second button on the page be that dark. It doesn't look that appealing and certainly not something we, as a company, would release as a product.

Additionally, we **were** missing a couple of variables (ones related to one of our most popular components -- the grid), say `$table-bg` was transparent; there were no variables for complex scenarios, like sorted cells. Variables weren't really interlinked as one would suspect. Some `border-color` variables were varying degrees of black with transparency while others were based on `$gray-` variables.

So the idea behind `_bootsrap-overrides.scss` came to be -- a file that would normalize (override) some bootstrap variables in such a way that it can be used by kendo-themes and Bootstrap. Right there you can begin to see the problem: why use Bootstrap in the first place, if we are going to override it?

Add he fact that we do add components faster than Bootstrap and at some point you are bound to get variable collision. I remember specifically well when the breadcrumb component was released -- it broke our already existing component big time...

What I am trying to say at great length is that in order to make things work we had to take architectural decisions that took as where we are today (and were at the time of the original post).

But the gist of it is that it's hard to rely completely on some else's variables. Which leads us to...

**`$color: null` is not a color**

In v4.43.0 and c4.44.0, we rely on hard coded variables. Those variables, `$error` in particular get their values from a map, that may be overridden. That tends to lead to problems. Take a look at the chip component:

https://github.com/telerik/kendo-themes/blob/8841c18b8c8f2b159bcd5ed316ce283c5de2fd7c/packages/bootstrap/scss/chip/_variables.scss#L72-L74

In v5.0.0 we did slightly better, by using a component specific map. True, that map still relies on another map, that has a generic name, but at least it's possible to fix the component map.

https://github.com/telerik/kendo-themes/blob/444e224c85edd153e7726d83c682d84e9215acd0/packages/bootstrap/scss/chip/_variables.scss#L67-L73

In v5.2.0 we finally got it right by using a unique, kendo specific name, for our theme colors:

https://github.com/telerik/kendo-themes/blob/01013f4f01ecce14973b008beff3076826fdabde/packages/bootstrap/scss/chip/_variables.scss#L67-L73

Why **exactly** is the original problem appearing, it's hard for me to say:

* looking at the stack trace, I can see that probably it's related to line 75 in the button theme, which comes from the default theme. Unfortunately, there is nothing wrong with that line

https://github.com/telerik/kendo-themes/blob/8841c18b8c8f2b159bcd5ed316ce283c5de2fd7c/packages/default/scss/button/_theme.scss#L72-L78

Here are the related lines in the variables file:

**Closed** 2022-08-26 16:39 UTC
Labels: bug, wontfix
