### ISSUE TITLE
Bootstrap removes some rtl behavior

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-themes#2569] opened 2021-06-22 07:38 UTC
**Describe the bug**
Content text not aligned in rtl cases - https://www.telerik.com/kendo-react-ui/components/layout/globalization/

**To reproduce**

1. Go to https://stackblitz.com/edit/react-bztele?file=index.html
1. Click TabStrip or Card
2. 
![image](https://user-images.githubusercontent.com/9494406/122883116-8c996780-d345-11eb-90dc-e9a553bbf508.png)
![image](https://user-images.githubusercontent.com/9494406/122883240-aaff6300-d345-11eb-90b8-49953896f35f.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/9494406/122883345-c66a6e00-d345-11eb-88f2-672f935caa45.png)
![image](https://user-images.githubusercontent.com/9494406/122883349-c8343180-d345-11eb-842e-8f7d44f62f3f.png)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Additional context**
When I remove the bootstrap link from the demo it is working correctly -    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

**Comment by joneff** [comment] 2021-06-22 08:05
The issue is caused by bootstrap explicitly providing left alignment for the body element. This can be fixed by a bit of styling on the page:

```
body {
    text-align: start;
}
```

That bit is not going to do justice in older browsers, but it's going to work fine for modern.

**Closed by joneff** 2021-06-22 08:05 UTC
Labels: invalid
