### ISSUE TITLE
[Grid] Alternate rows

### ISSUE THREAD

**Issue by cheng93** [telerik/kendo-themes#4289] opened 2023-02-14 13:34 UTC
**Describe the bug**
When importing the grid scss module `@progress/kendo-theme-default/scss/grid/` alternate rows are not working

**To reproduce**

https://stackblitz.com/edit/angular-rpyh9n?file=src%2Fstyles.scss,angular.json

**Expected behavior**

Alternate rows should be different colours

**Screenshots**
![image](https://user-images.githubusercontent.com/13205912/218753556-3b78c919-2242-44f6-8c2e-95ca850ad5a8.png)

**Affected package (please remove the unneeded items)**
6.1.0

* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by cheng93** [comment] 2023-02-14 13:43
I believe the issue is in scss, it is `k-table-alt-row`

however the component uses `k-table-row-alt`

**Comment by joneff** [comment] 2023-02-21 08:10
@JoomFX  @TeyaVes any thoughts?

**Comment by JoomFX** [comment] 2023-02-21 09:07
The issue is fixed in the [latest version (11.2.0)](https://www.npmjs.com/package/@progress/kendo-angular-grid) of Kendo Angular Grid.

**Closed by JoomFX** 2023-02-21 09:07 UTC
Labels: bug
