### ISSUE TITLE
[Grid] Edit buttons misalignment

### ISSUE THREAD

**Issue by slavenai** [telerik/kendo-themes#4702] opened 2023-09-19 07:54 UTC
When the user clicks the Edit button, the Update and Cancel buttons appear misaligned compared to the Edit and Remove buttons on the other rows:
https://stackblitz.com/edit/angular-bnprhy?file=src%2Fapp%2Fapp.component.ts

**Screenshots**
Current behavior:
![image](https://github.com/telerik/kendo-angular/assets/108671673/7e2f5e32-1c1a-41a5-bf01-13258408936a)

Expected behavior: 
![image](https://github.com/telerik/kendo-angular/assets/108671673/73b945bc-b76c-46c3-a04b-92129a2842c3)

**Comment by JoomFX** [comment] 2023-10-31 15:58
This can be fixed (improved) if we use `gap` instead of `margin`:

https://stackblitz.com/edit/angular-ailcee?file=src%2Fapp%2Fapp.component.ts

**Comment by JoomFX** [comment] 2023-11-02 09:46
It turned out that the Flexbox (`gap`) workaround above is not a viable solution mostly because it sets `display: flex;` to the Table Cell while it should preferable be `display: table-cell;`. This, in turn, while fixing the reported misalignment causes other misalignments.

Since the issue is caused by the rendering in the Angular Grid (all buttons are rendered and the unneeded ones are hidden with `display: none;`) it is not something that necessarily need to be addressed in Kendo Themes.
At the same time, it is quite tricky to be address in the component, because it is a template and we allow the user to place whatever buttons they want there (and with whatever order they want).

A possible solution, **which will require rendering changes**, is to wrap the buttons in a container and set the container to `display: flex;`, no the cell itself.
Such a solution needs to be discussed and synced between the different teams.

@Juveniel @stnikolova @dtopalov

**Closed** 2023-11-06 08:36 UTC
