### ISSUE TITLE
FileManager - Design discrepancies

### ISSUE THREAD

**Issue by LYacheva** [telerik/kendo-themes#3039] opened 2021-12-08 11:55 UTC
While turning the FileManager into a Figma component, I've encountered several mismatches between design and FE implementation:

1. Content area - Grid View
- The grid cell icon should be horizontally aligned with the text instead of stacked on top of it

Original design:
<img width="1028" alt="Screenshot 2021-12-08 at 13 36 20" src="https://user-images.githubusercontent.com/89079450/145202093-f2a787cc-a5ec-4971-8923-9117d355fc58.png">

Implementation:
<img width="1065" alt="Screenshot 2021-12-08 at 13 37 23" src="https://user-images.githubusercontent.com/89079450/145202201-bc63c326-f4d2-4c7e-b5b7-9209e8a62517.png">

2. Breadcrumb 
- The selected item should not appear as Disabled

<img width="1061" alt="Screenshot 2021-12-08 at 13 41 09" src="https://user-images.githubusercontent.com/89079450/145202655-6dcb16e5-6d14-4cbc-aadf-f37ddcadb845.png">

- The Breadcrumb panel should have background and bottom border + refer to Figma file for size metrics (React only)

<img width="1418" alt="Screenshot 2021-12-08 at 13 46 55" src="https://user-images.githubusercontent.com/89079450/145203508-76e6fc26-6e55-44f0-bd48-690bc83136c1.png">

3. Splitbar - Border
- Left & right borders were added to the Splitbar component (only in the context of FileManager) in order to visually separate the content (use Figma for reference)

<img width="564" alt="Screenshot 2021-12-08 at 13 44 40" src="https://user-images.githubusercontent.com/89079450/145203083-d0ae4a04-2043-4fdf-bd9b-2b3126caf348.png">

4. Rename (React only)
- Rename function should be enabled by inline editing instead of Dialog window

<img width="1436" alt="Screenshot 2021-12-08 at 13 48 54" src="https://user-images.githubusercontent.com/89079450/145203867-9a93db43-a595-4b99-a7f8-ec7c56d78af3.png">

<img width="1088" alt="Screenshot 2021-12-08 at 13 51 43" src="https://user-images.githubusercontent.com/89079450/145204044-41ad81b2-bdf4-485f-a19e-1f3068b328db.png">

**Comment by silviyaboteva** [comment] 2022-01-19 12:38
React implementation: https://www.telerik.com/kendo-react-ui/components/sample-applications/file-manager/
jQuery implementation: https://demos.telerik.com/kendo-ui/filemanager/index

> Please check whether there are issues with the styles or inside the implementation of the FileManager.

**Comment by epetrow** [comment] 2022-01-20 15:30
Here are my comments on the above:

1. Content area - Grid View (JQuery): 

-  The icon and text are stacked on top of each other because of two things: 

    1. A wrapper div with class _file-group-icon_ which overrides the display property of the span inside it;
    2. An incorrect class _file-name_ which is used on the div containing the text, _k-file-name_ should be used instead;

Removing the div and applying the correct class name will align the icon and text horizontally as is by design.

2. Breadcrumb: 

- The selected items should not appear as disabled (JQuery only): This is related to https://github.com/telerik/kendo-themes/issues/3004

- The Breadcrumb panel should have background and bottom border + refer to Figma file for size metrics (React only): 

  Class _k-filemanager-breadcrumb_ should also be added to the nav

3. Splitbar - Border:

- Left & right borders were added to the Splitbar component (only in the context of FileManager) in order to visually separate the content (use Figma for reference): 

  Border styles were added here: https://github.com/telerik/kendo-themes/pull/3267

4. Rename (React only):

- To be discussed further

**Comment by silviyaboteva** [comment] 2022-02-04 07:47
Closing this as theme-related tasks are merged in develop branch and component-related tasks are opened in KendoReact and Kendo jQuery suites.

**Closed by silviyaboteva** 2022-02-04 07:47 UTC
