### ISSUE TITLE
ColorPalette cannot be disabled in SASS themes

### ISSUE THREAD

**Issue by IKKI2000** [telerik/kendo-themes#1053] opened 2019-11-06 02:26 UTC
### Bug report
ColorPalette cannot be disabled in SASS themes. The issue is not reproducible in LESS themes.

### Reproduction of the problem
```css
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.3.1023/styles/kendo.default-v2.min.css">
```
```html
<div id="paletteDisabled"></div>
```
```js
$('#paletteDisabled').kendoColorPalette().data('kendoColorPalette').enable(false);
```

1. Run the following [Dojo snippet](https://dojo.telerik.com/ABiVOluD)

### Current behavior
ColorPalette is enabled

### Expected/desired behavior
ColorPalette is disabled

### Environment
* **Kendo UI version:** 2019.3.1023
* **jQuery version:** 1.12.4
* **Browser:** all

**Comment by Juveniel** [comment] 2020-02-13 09:16
The described issue can only be observed in Kendo jQuery ColorPicker where an overlay is used when the widget is disabled. Instead, the ColorPicker wrapper should receive a `.k-state-disabled` class. 

The issue is resolved with [the following PR](https://github.com/telerik/kendo/pull/10641) in Kendo jQuery. Closing this issue.

**Closed by Juveniel** 2020-02-13 09:16 UTC
Labels: C:Colorpicker, FP: Planned, FW:jQuery, T:Bootstrap, T:Default, T:Material, bug
