### ISSUE TITLE
Styles problem

### ISSUE THREAD

**Issue by Miedziaq** [telerik/kendo-themes#4160] opened 2022-12-09 10:31 UTC
How is it possible that angular 14-15 with your newest mackages not working? Styles not loading, there are many warning that ~ is deprecated in imports on example

**node_modules\@progress\kendo-theme-bootstrap\scss\signature\_theme.scss' imports '~@progress/kendo-theme-default/scss/signature/_theme.scss' with a tilde. Usage of '~' in imports is deprecated.

"@progress/kendo-theme-bootstrap": "^5.12.0",  THE NEWEST
"bootstrap": "^5.2.1",   The same as on your github codes** 

looks like ugly guy, even buttons its wrong styled, your package uses ~ in import styles, this is deprecated !

whole system, big enterprise system based on kendo is broken and much hours we lost to style it to fix everything, its a joke ...

some of old packages from kendo installed was because your newest precedent package need some older version from other package, so it is impossible to get all packages newest. there is much dependency problems....

**Affected package (please remove the unneeded items)**
  "@progress/kendo-angular-buttons": "^8.2.2",
    "@progress/kendo-angular-common": "^3.2.2",
    "@progress/kendo-angular-dateinputs": "^7.1.6",
    "@progress/kendo-angular-dialog": "^7.1.5",
    "@progress/kendo-angular-dropdowns": "^7.2.4",
    "@progress/kendo-angular-editor": "^4.2.0",
    "@progress/kendo-angular-excel-export": "^5.0.2",
    "@progress/kendo-angular-grid": "^7.4.2",
    "@progress/kendo-angular-inputs": "^9.0.3",
    "@progress/kendo-angular-intl": "^4.1.1",
    "@progress/kendo-angular-l10n": "^4.0.1",
    "@progress/kendo-angular-layout": "7.2.0",
    "@progress/kendo-angular-notification": "^4.0.1",
    "@progress/kendo-angular-pdf-export": "^4.0.1",
    "@progress/kendo-angular-popup": "^5.0.2",
    "@progress/kendo-angular-progressbar": "^3.1.2",
    "@progress/kendo-angular-scrollview": "^5.0.2",
    "@progress/kendo-angular-toolbar": "^6.1.2",
    "@progress/kendo-angular-tooltip": "^4.1.1",
    "@progress/kendo-angular-treeview": "^7.1.5",
    "@progress/kendo-angular-upload": "^9.0.4",
    "@progress/kendo-data-query": "^1.6.0",
    "@progress/kendo-drawing": "^1.17.2",
    "@progress/kendo-licensing": "^1.2.2",
    "@progress/kendo-theme-bootstrap": "^5.12.0",
    "@progress/kendo-theme-default": "^5.12.0",
**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* All

**Comment by joneff** [comment] 2022-12-14 22:37
Duplicate of #3963

**Closed by joneff** 2022-12-14 22:37 UTC
Labels: bug
