### ISSUE TITLE
Misaligned cells in DAY&WEEK view

### ISSUE THREAD

**Issue by ipeshev** [telerik/kendo-themes#554] opened 2019-01-16 12:22 UTC
## I'm submitting a...

* Bug report 

## Current behavior
![problem](https://user-images.githubusercontent.com/4143177/51248708-b2aec680-1999-11e9-9035-b681f7558980.png)

## Minimal reproduction of the problem with instructions
1.Open this demo https://www.telerik.com/kendo-angular-ui-develop/components/scheduler/
2.Choose material theme
3.On bootstrap theme it is not working at all

## Environment
Product:

* Kendo Ui for jQuery
* Kendo Ui for Angular
* Kendo Ui for React
* Kendo Ui for Vue

Package versions:

```

```

Browser:

- Chrome (desktop) version XX
- Chrome (Android) version XX
- Chrome (iOS) version XX
- Firefox version XX
- Safari (desktop) version XX
- Safari (iOS) version XX
- IE version XX
- Edge version XX

System:
- TypeScript version: XX 
- Node version: XX  
- Platform:

**Comment by mparvanov** [comment] 2019-02-12 13:42
The cells are aligned in Kendo jQuery Day and Week views.

**Comment by joneff** [comment] 2019-02-12 13:43
The issue is related only to material + kendo-angular and the issue is fixed in the develop branch

**Closed by joneff** 2019-02-12 13:43 UTC
Labels: C:Scheduler, bug
