### ISSUE TITLE
There is space between buttons inside a button group

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#658] opened 2019-03-12 15:49 UTC
## I'm submitting a...

* Bug report 

## Current behavior
When nesting a ButtonGroup or a KendoToolbar that contains a button group inside a kendoGridToolbarTemplate there is space between the grouped buttons.

## Expected behavior
There should not be space between grouped buttons.

## Minimal reproduction of the problem with instructions
Check the following example:
https://stackblitz.com/edit/angular-ysa3kb-jtlniu?file=app/app.component.ts

## Workaround
add the following custom CSS:
`
   .k-button-group {        
     margin-left: 8px;      
   }
   .k-button-group .k-button+.k-button {
       margin-left: 0;
   } 
`
https://stackblitz.com/edit/angular-ysa3kb-tqjvqw?file=app/app.component.ts

## Environment
Product:
* Kendo Ui for Angular

**Comment by TeyaVes** [comment] 2019-06-05 10:55
duplicate of https://github.com/telerik/kendo-themes/issues/751

**Closed by TeyaVes** 2019-06-05 10:55 UTC
Labels: T:Default, bug
