### ISSUE TITLE
Define UX guide for cards in chat

### ISSUE THREAD

**Issue by joneff** [telerik/kendo-themes#176] opened 2018-05-14 11:04 UTC
How should card behave:

* should they be as wide as the container
* should they be fixed width
* when in deck, group, list etc, how wide should they be
* when a deck, group, list etc, has only one card, how should it behave?

/cc @lkarakoleva 

When the guides are clear, we'll implement it in the cards / chat

**Comment by lkarakoleva** [comment] 2018-05-16 14:15
The width of the card depends on the container:

Stand alone card / deck card / group card
- single card is 100% width of the container;
- 2 cards are 50% width of the container;
- for more than 2 cards container width is equally separated by the number of cards till its min-width=260px, than we have scrollable navigation buttons

Chat card / deck card / group card:
- single card is 80% of the chat area which is the max with of a message;
- for more than 2 cards container width is equally separated by the number of cards till its min-width=240px, than we have scrollable navigation buttons

List card:
- a card width is equal to a column width

![cards](https://user-images.githubusercontent.com/16577622/40119332-10903904-5925-11e8-8301-06877b6c8bc9.png)

**Comment by elena-gancheva** [comment] 2019-10-24 13:46
Closing this issue, since it is not a bug or enhancement report. The issue for the card related styles is referenced #989

**Closed by elena-gancheva** 2019-10-24 13:46 UTC
Labels: C:Chat, Enhancement
