### ISSUE TITLE
Foreground and background color picker tools are not aligned as expected in Firefox

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-themes#747] opened 2019-05-21 13:07 UTC
## I'm submitting a...

* Bug report 

## Current behavior

Foreground and background color picker tools are not aligned as expected in Firefox.

## Expected behavior

All tools should be aligned in the same way.

## Minimal reproduction of the problem with instructions

Open this demo in Firefox: https://www.telerik.com/kendo-angular-ui/components/editor/tools/

![2019-05-21_1605](https://user-images.githubusercontent.com/1486568/58098457-53c8ba80-7be2-11e9-8c0b-43f19a67d857.png)

## Environment
Product:

* Kendo Ui for Angular

Browser:

- Firefox version XX

The issue cannot be reproduced in Chrome.

**Comment by KeiBlag** [comment] 2019-06-11 12:44
The issue is fixed with https://github.com/telerik/kendo-themes/pull/732.

**Closed** 2019-06-12 10:20 UTC
Labels: C:Colorpicker, C:Editor, bug
