### ISSUE TITLE
SASS Compilation Error:  Undefined variable: "$primary-button-hovered-bg" (and more...)

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-themes#2033] opened 2020-11-03 15:39 UTC
**Describe the bug**
When trying to build CSS for the grid by **only** importing the grid SCSS, it is not possible to compile the SASS.  Numerous undefined variable errors are presented.  Some include:
`$primary-button-hovered-bg`
`$button-hovered-bg`
`$toolbar-padding-x`
`$toolbar-padding-y`
`$input-border`

**To reproduce**

package.json
``` json
{
    "name": "kendo-test",
    "version": "0.0.1",
    "scripts": {
        "build": "npm rebuild node-sass && webpack --mode development --watch --progress"
    },
    "private": true,
    "dependencies": {
        "@progress/kendo-theme-bootstrap": "^4.23.1",
        "bootstrap": "^4.5.3",
        "popper.js": "^1.16.1"
    },
    "devDependencies": {
        "autoprefixer": "^10.0.1",
        "core-js": "^3.6.5",
        "css-loader": "^5.0.0",
        "extract-loader": "^5.1.0",
        "file-loader": "^6.2.0",
        "node-sass": "^4.14.1",
        "postcss-calc": "^7.0.5",
        "postcss-loader": "^4.0.4",
        "sass-loader": "^10.0.5",
        "style-loader": "^2.0.0",
        "webpack": "^4.44.2",
        "webpack-cli": "^4.1.0"
    }
}
```

webpack.config.js
``` js
const path = require("path");

module.exports = (env = {}, argv = {}) => {
    const libPath = path.resolve(__dirname, "../wwwroot/lib");
    const distPath = path.resolve(__dirname, "../wwwroot/dist");

    return {
        watch: true,
        watchOptions: {
            ignored: /node_modules/
        },
        mode: argv.mode || "development",
        entry: {
            themeLight: ["./styles/themeLight.scss"]
        },
        output: {
            filename: "[name].js",
            path: distPath
        },
        module: {
            rules: [
            {
                test: /.scss$/i,
                use: [
                    // Creates `style` nodes from JS strings
                    'style-loader',
                    // Translates CSS into CommonJS
                    'css-loader',
                    // PostCSS
                    {
                        loader: 'postcss-loader',
                        options: {
                            precision: 10,
                            plugins: [
                                require('autoprefixer')(),
                                require('postcss-calc')()
                            ]
                        }
                    },
                    // Compiles Sass to CSS
                    {
                        loader: 'sass-loader',
                        options: {
                            implementation: require('node-sass'),
                            // implementation: require('dart-sass'),
                            sassOptions: {
                                precision: 10,
                                // fiber: require('fibers')
                            }
                        }
                    }
                ]
            }
        ]
        }
    };
};
```

themeLight.scss
``` scss
@import "~@progress/kendo-theme-bootstrap/scss/grid";
```

**Expected behavior**
We should be able to, as your docs suggest, import the individual components instead of having to use the all.scss.

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Not Applicable

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment] 2020-11-04 16:35
Duplicate of #1973. Please refer to it and the related PR.

Note: you can test the validity of the fix by using the code in `verify-sass` branch.

**Closed by joneff** 2020-11-04 16:35 UTC
Labels: bug

**Comment by joneff** [comment] 2020-11-05 15:37
The themes are out

```
