### ISSUE TITLE
PivotGrid - Discrepancies

### ISSUE THREAD

**Issue by imasyuko** [telerik/kendo-themes#2973] opened 2021-11-19 09:54 UTC
While drawing the PivotGrid component in Figma UI Kits for all three themes I came across some discrepancies between design and implementation.

**Default**

1. Missing padding between the icon and the text in pivotgrid cells.
          
_design_    <img width="412" alt="Screenshot 2021-11-19 at 9 56 01" src="https://user-images.githubusercontent.com/81818548/142592764-ca7f62d7-d16c-4dc2-a5c6-17795aadae1c.png">                                    

_implementation_    <img width="315" alt="Screenshot 2021-11-19 at 9 54 06" src="https://user-images.githubusercontent.com/81818548/142592672-7eb02d55-b47a-4fea-bf32-4328d5aaed1c.png">

2. The height of the configuration button is 28px by design. In the implementation is 30px.
       
_design_    <img width="278" alt="Screenshot 2021-11-19 at 9 58 41" src="https://user-images.githubusercontent.com/81818548/142592929-6b563d58-3ae3-40ba-8d41-d9a5b57d9321.png">

_implementation_    <img width="197" alt="Screenshot 2021-11-19 at 9 59 54" src="https://user-images.githubusercontent.com/81818548/142593039-44b7f72c-24f4-48a5-9374-d0210ec285e6.png">

3. Filters are not shown in the demo.

_design_     <img width="349" alt="Screenshot 2021-11-19 at 10 01 42" src="https://user-images.githubusercontent.com/81818548/142593235-d9e23a5b-b156-4b68-b66b-da778007d4bf.png"> 
                                      
_implementation_     <img width="318" alt="Screenshot 2021-11-19 at 10 02 20" src="https://user-images.githubusercontent.com/81818548/142593255-df721eb0-ed2a-43c7-a0e0-63998e240761.png">

4. The background of the popup – is it $base-bg, or $component-bg?

_design_    <img width="543" alt="Screenshot 2021-11-19 at 10 06 56" src="https://user-images.githubusercontent.com/81818548/142593616-4149f5b0-90d9-4fb4-86d8-1be8fc57a6b6.png">
                                             
_implementation_     <img width="379" alt="Screenshot 2021-11-19 at 10 07 16" src="https://user-images.githubusercontent.com/81818548/142593518-bf27f3ef-bea6-4313-bd89-d4bc95dfc946.png">

5. Missing navigation arrows in popup list items in the implementation. 
_(see the screenshots above)_

6. In the implementation of the setting panel’s content (both vertical and horizontal) there are 2px top and bottom paddings.
      
_horizontal_
<img width="939" alt="Screenshot 2021-11-19 at 10 11 12" src="https://user-images.githubusercontent.com/81818548/142594028-9e1dd449-6204-4e2a-ae78-4a88fc54e4ea.png">
 

_vertical_ 
<img width="478" alt="Screenshot 2021-11-19 at 10 10 14" src="https://user-images.githubusercontent.com/81818548/142594060-c1217a63-717a-4de4-baa2-2952797cc6ff.png">

7. There are some odd 5px top padding of the Field label in the horizontal settings panel.

<img width="557" alt="Screenshot 2021-11-19 at 10 12 49" src="https://user-images.githubusercontent.com/81818548/142593993-41220d34-e928-4b0a-b3e0-82ddc1f900a4.png">

**Bootstrap**

1. The background of the total pivotgrid cells is different in the design file.
_design_   
<img width="763" alt="Screenshot 2021-11-19 at 10 16 43" src="https://user-images.githubusercontent.com/81818548/142594943-f25cde0f-f103-4fa6-8613-4404fbaef0b4.png">

_implementation_  

<img width="749" alt="Screenshot 2021-11-19 at 10 17 51" src="https://user-images.githubusercontent.com/81818548/142594969-0100afd7-a52d-4751-9934-7091ac9555b5.png">
2. In the horizontal settings panel there are some odd 5px top padding of Field label.

<img width="622" alt="Screenshot 2021-11-19 at 10 19 56" src="https://user-images.githubusercontent.com/81818548/142594587-5f43230c-11a0-4276-9114-eb9ce178fc85.png">

**Material**

1. Total pivotgrid cells and those in hover/focused state have the same background in the implementation (states are not shown in the design).

<img width="443" alt="Screenshot 2021-11-19 at 10 21 18" src="https://user-images.githubusercontent.com/81818548/142594557-e8754099-2790-4f1c-b9df-74f5f73b0664.png">

cc: @ivelina-penkova

**Comment by epetrow** [comment] 2022-02-01 10:03
Pivotgrid Design Discrepancies

Default 

1. Missing padding between icon and text in pivotgrid cells: Missing padding has been added here: https://github.com/telerik/kendo-themes/pull/3329

2. The height of the configuration button is 28px by design. In the implementation is 30px: Checked in the design files and the configudation button height is 30px as is implemented

![image](https://user-images.githubusercontent.com/95700708/151932126-68e71c73-37c0-4580-a2c1-9123eed4d513.png)


3. Filters are not shown in the demo: This is a not a theme related issue, as filters have not been implemented yet. 
An issue will be logged with both suites implementing the component.

4. The background of the popup – is it $base-bg, or $component-bg?: It is $component-bg

5. Missing navigation arrows in popup list items in the implementation: Not an issue with the themes as the navigation arrows are present in the visual tests

![image](https://user-images.githubusercontent.com/95700708/151936561-8922e520-fbf8-4790-9876-d199590c7f3e.png)

An issue will be logged with both suites implementing the component.

6. In the implementation of the setting panel’s content (both vertical and horizontal) there are 2px top and bottom paddings: I see no discrepancy here as the top and bottom paddings are present in the design as well

![image](https://user-images.githubusercontent.com/95700708/151936985-426401e2-8b2e-4f9e-bf62-3482333effbf.png)


7. There are some odd 5px top padding of the Field label in the horizontal settings panel: This padding serves to align the elements in the form layout which is used in the implementation

Bootstrap

1. The background of the total pivotgrid cells is different in the design file: In the implementation we use a solid color but it is basically the same as the one in the design. Could you please provide a design for a hovered row including the total cells?


2. In the horizontal settings panel there are some odd 5px top padding of Field label: Here the padding is also needed to align the elements in the form layout

Material

1. Total pivotgrid cells and those in hover/focused state have the same background in the implementation (states are not shown in the design): Could you specify what background should be applied here since it is not shown in the design?

**Closed** 2022-02-04 07:37 UTC
