### ISSUE TITLE
Primary button hovered and pressed colors in Material

### ISSUE THREAD

**Issue by alpkarli** [telerik/kendo-themes#685] opened 2019-04-10 11:09 UTC
Primary button hovered and pressed colors are not injected into style of the material theme. 

Their variables are: 

$primary-button-hovered-bg
$primary-button-pressed-bg

**Comment by joneff** [comment] 2019-05-29 14:54
@alpkarli, the issue is invalid and I am closing it.

If you need assistance how to customize the buttons, although it will break compliance with Material Design, you can file a ticket trough our support system.

**Closed by joneff** 2019-05-29 14:54 UTC
Labels: invalid
