### ISSUE TITLE
Cannot customize the background color of the main wrapping element for the TileLayout in Bootstrap Theme

### ISSUE THREAD

**Issue by svdimitr** [telerik/kendo-themes#1887] opened 2020-09-17 07:42 UTC
**Describe the bug**
The `Component bg` does not alter the background color of the main wrapping element for the TileLayout component. 

**To reproduce**

1. Go to the Blazor theme builder (https://themebuilder.telerik.com/blazor-ui)
1. Choose the Bootstrap Theme 
1. Select the TileLayout component
1. Alter the `component bg` color
1. See that it changes only the background color of the tiles, but not the color of the main wrapping element

**Expected behavior**
The `Component bg` should change the background color of the main wrapping element too

**Screenshots**

![tilelayout-component-bg-color](https://user-images.githubusercontent.com/61150560/93435650-66d0c500-f8d2-11ea-9a0f-95c5d56a9b62.png)

**Affected package (please remove the unneeded items)**
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment] 2020-12-18 13:36
The issue is not formulated correctly: the background color of the main wrapping element **can** be customized, because there is a variable for that.

It cannot in be customized in the context of theme builder, which is completely different.

**Comment by svdimitr** [comment] 2020-12-18 13:38
@joneff indeed, it cannot be customized in the context of the ThemeBuilder, excuse me for the mistake

**Comment by joneff** [comment] 2022-12-01 00:14
ThemeBuilder Pro can customize it. Closing as won't fix.

**Closed by joneff** 2022-12-01 00:14 UTC
Labels: wontfix, C:TileLayout, interop:ThemeBuilder, integration
