### ISSUE TITLE
Error: Can't find stylesheet to import. (Fluent Theme)

### ISSUE THREAD

**Issue by kdubious** [telerik/kendo-themes#5119] opened 2024-07-22 18:58 UTC
**Describe the bug**
When following instruction on NPM to configure the Fluent theme, I'm struck by the following error

``
Error: Can't find stylesheet to import.
  ╷
2 │ @use "@progress/kendo-theme-core/scss/color-system/_functions.import.scss" as functions;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@progress\kendo-theme-fluent\scss\core\color-system\_swatch.scss 2:1  @use
  node_modules\@progress\kendo-theme-fluent\scss\core\_index.scss 4:1                @forward
  node_modules\@progress\kendo-theme-fluent\scss\index.scss 2:1                      @use
``

**To reproduce**

Follow the steps from here: https://www.npmjs.com/package/@progress/kendo-theme-fluent
SCSS Variables Customization

**Expected behavior**
I expect to get a valid css file

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-fluent

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**

* OS: [Windows]
* Node version: [16.17.1]
* NPM version: [8.15.0]

**Additional context**
running "sass"

**Comment by epetrow** [comment] 2024-07-30 08:21
Hey @kdubious, could you please send the contents of your `scss` file or provide a simple demo as I am unable to reproduce the issue?

**Comment by epetrow** [comment] 2024-08-08 07:36
@kdubious, have you managed to compile the theme or do you still require assistance?

**Comment by epetrow** [comment] 2024-08-13 13:38
Closing this thread as I am unable to reproduce the issue.

**Closed by epetrow** 2024-08-13 13:38 UTC

**Comment by epetrow** [comment] 2024-11-28 09:04
Hey @kdubious, from what I am able to infer from your example it seems to me Sass does not know in which directory to look for when importing files. 

My assumption is based on the compilation example you've given and that I am only able to reproduce this if I ommit `--load-path` from the Sass CLI. 

Could you please try compiling with `sass --load-path="node_modules" .\kendo .\output.css` and let me know what the outcome is? Also please note that the path to node_modules might be different than the one I have given in the example.

**Comment by kdubious** [comment] 2024-12-02 21:10
@epetrow Sounds correct... was unaware of that flag. I will try and report back

**Comment by kdubious** [comment] 2024-12-02 21:29
@epetrow this works, thanks!

Is there a way to do things with the "old style", like the way Bootstrap does? In other words, I have a Variables scss file that I typically import first, then I import the Kendo SCSS. The new docs make it look like I need to pass my variables inside of the @use:

```
@use "../../node_modules/@progress/kendo-theme-fluent/scss/all.scss" as kendo-theme with (
    
    // @import "./variables"; -- Sadly, this fails

    $kendo-body-bg: beige,
    $kendo-font-size: 1rem
);
```

**Comment by epetrow** [comment] 2024-12-03 09:04
@kdubious, dart-sass does not allow this unfortunatelly, even though you could still use `@import`, which is not recommended. What we have described in our new docs is based on the official [Sass documentation](https://sass-lang.com/documentation/at-rules/use/#configuration).
