### ISSUE TITLE
Text overflow in virtual DropDownList in Blazor

### ISSUE THREAD

**Issue by ivanchev** [telerik/kendo-themes#2462] opened 2021-05-07 08:21 UTC
**Describe the bug**
In a Blazor virtualized DropDownList, when an item has longer text it overflows.

**Expected behavior**
The behavior should be the same as in a non-virtualized DropDownList

**Screenshots**

https://user-images.githubusercontent.com/5861835/117132266-485d0280-adab-11eb-970e-abc60eeea941.png

**Affected package (please remove the unneeded items)**
* theme-bootstrap
* theme-material

**Affected suites (please remove the unneeded items)**
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Comment by silviyaboteva** [comment] 2021-05-27 14:16
The problem seems to be caused by an inline `height` set to the items in the list. Once the style is removed, the issue will be fixed. @ivanchev, can you confirm?

**Comment by joneff** [comment] 2022-01-19 08:36
fixed by 6f45cf0e1c4aeeca31cf8607e7f5b16f51dec598

**Closed by joneff** 2022-01-19 08:36 UTC
Labels: bug, C:Autocomplete, C:Combobox, C:Dropdownlist, FW:Blazor
