### ISSUE TITLE
Ripple effect offset for checkboxes and radios

### ISSUE THREAD

**Issue by danielkaradachki** [telerik/kendo-themes#1136] opened 2019-12-23 14:09 UTC
**Describe the bug**
The ripple effect is not shown on the correct position for checkboxes and radio buttons.

**To reproduce**
1. Go to https://www.telerik.com/kendo-angular-ui/components/ripple/
2. Click on a checkbox or a radio button

**Expected behavior**
The effect is shown over the input

**Affected package (please provide)**
* theme-default
* theme-bootstrap
* theme-material

**Affected suites (please provide)**
* Kendo UI for Angular
* Kendo UI for React

**Comment by TeyaVes** [comment] 2019-12-23 14:14
duplicate of: https://github.com/telerik/kendo-themes/issues/1111

**Closed by TeyaVes** 2019-12-23 14:14 UTC
Labels: C:Ripple, FW:Angular, FW:React, T:Bootstrap, T:Default, T:Material, bug
