### ISSUE TITLE
Buttons overlap in Grid when in editing mode

### ISSUE THREAD

**Issue by keiblag** [telerik/kendo-themes#817] opened 2019-07-15 11:25 UTC
## I'm submitting a...

* Bug report 

## Current behavior
When the Grid component is in editing mode and the width of the column that holds the command buttons is not big enough, they overlap.

![grid](https://user-images.githubusercontent.com/10484594/61212509-2cd2c480-a70b-11e9-8f50-31255a0c7722.PNG)

## Expected behavior
The buttons shouldn't overlap.

## Minimal reproduction of the problem with instructions
https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-reactive-forms/

  1. Click button Add new
  2. In column command see the buttons overlap

## Environment
Product:

* Kendo Ui for Angular

**Comment by TeyaVes** [comment] 2019-07-24 15:12
duplicate of https://github.com/telerik/kendo-themes/issues/239

**Closed by TeyaVes** 2019-07-24 15:12 UTC
Labels: C:Grid, T:Bootstrap, T:Default, T:Material, bug

**Comment by joneff** [comment] 2020-02-13 15:56
Fixed by #1226
