### ISSUE TITLE
The kendoSassBuild method of the @progress/kendo-theme-tasks throws an error

### ISSUE THREAD

**Issue by PekoPPT** [telerik/kendo-themes#4185] opened 2022-12-27 12:36 UTC
**Describe the bug**
When using the **kendoSassBuild** method, the following error appears:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/41293735/209667327-198d6543-518b-4a4d-80d4-cd6e7b7ecac4.png">

**To reproduce**
1. Clone [this repository](https://github.com/silviyaboteva/kendo-react-dark-mode)
2. Make a fresh packages install
3. Run `npm run start`

**Expected behavior**
The project should start smoothly and with no issues

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for React

**Comment by joneff** [comment] 2023-01-03 09:41
The issue is not related to the themes. closing

**Closed by joneff** 2023-01-03 09:41 UTC
Labels: invalid
