### ISSUE TITLE
Strange symbols in Grid's Pager

### ISSUE THREAD

**Issue by iordanGrancharov** [telerik/kendo-themes#5234] opened 2024-11-15 10:26 UTC
**Describe the bug**
The pager's dropdown has some strange characters when using Kendo UI for jQuery without a meta charset attribute set to utf-8.  This occurs only in Chrome and Edge when the Grid and when the Grid is on a larger screen.   The issues seem to be produced by the `k-list-item-text` class. The issue appears with v10.0.0 of the Kendo Themes. 

Adding the meta tag with charset utf-8 fixes the issue. However in this [simple example](https://dojo.telerik.com/ZVrkVYWh), the issue is still present even with the meta tag added.

**To reproduce**

1. Go to [this Kendo UI Dojo](https://dojo.telerik.com/RCYDQRoP) for code reference and this [full screen version of it.](https://runner.telerik.io/fullscreen/RCYDQRoP)
2. Open the Pager's PageSizes Dropdown in the full screen.

**Current behavior**
![Image](https://github.com/user-attachments/assets/bf40e4f7-e2ea-4698-87a9-7a634ccca988)

**Current behavior**
![Image](https://github.com/user-attachments/assets/9c7af23b-a202-47a8-94ef-5ca09455e3b3)

**Affected package**
* theme-default

**Affected suites**
* Kendo UI for jQuery

**Affected browsers**
* Chrome version: [131]
* Edge version: [130]

**Comment by epetrow** [comment] 2024-12-06 15:32
It turns out that our build tool `sass-build` was stripping the `@charset` character encoding from the compiled css, which would result in the issue being present even if there is a `<meta>` tag.

With the deprecation of `sass-build` in [5245](https://github.com/telerik/kendo-themes/pull/5245), this is no longer reproducible so I think we can close this now. You can see the following [dojo](https://dojo.telerik.com/ivozhFam/3) for reference.

**Closed** 2024-12-09 08:43 UTC
Labels: Bug
