### ISSUE TITLE
Material Sky Dark swatch DropDownList issue

### ISSUE THREAD

**Issue by epetrow** [telerik/kendo-themes#3266] opened 2022-01-20 12:15 UTC
**Describe the bug**
When applying the Material Sky Dark theme, using the "@progress/kendo-theme-material": "^5.0.0" package, and including both of them in CSS (not SCSS form) that the Telerik DropDownList control ("@progress/kendo-react-dropdowns": "^4.14.1"), it does not theme the list that drops down from the control when the down arrow is selected.

**To reproduce**

1. Go to 'https://themebuilder.telerik.com/kendo-react-ui'
1. Select DropDownList component
1. Make sure Sky Dark swatch is selected

**Expected behavior**
DropDownList component to have black background color and white text color.

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by Juveniel** [comment] 2022-01-25 07:13
@epetrow could you please check the latest [ThemeBuilder](https://themebuilder.telerik.com/kendo-react-ui) where the 5.1.0 version of the themes is used and verify if the issue is resolved in the React preview ?

**Comment by epetrow** [comment] 2022-01-25 08:34
Hey @Juveniel, I just checked and can confirm this is resolved

**Closed** 2022-01-25 08:35 UTC
Labels: bug, C:Dropdownlist, T:Material
