### ISSUE TITLE
The KendoReact Grid no records template is shown only in the first column.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-themes#790] opened 2019-06-17 12:42 UTC
The KendoReact Grid no records template is shown only in the first column.

![image](https://user-images.githubusercontent.com/11087921/59605036-7d5bff80-9116-11e9-86a0-0ab9ca7d73dd.png)

It seems to be related to this change:

https://github.com/telerik/kendo-themes/pull/746/commits/3cbe04fc98757db5656b74da730988b78255d8ac

**Comment by TeyaVes** [comment] 2019-06-17 13:13
duplicate of: https://github.com/telerik/kendo-themes/issues/781

**Closed** 2019-06-17 13:13 UTC
Labels: C:Grid, bug
