### ISSUE TITLE
Grid columns with filtering menu has header text align different from columns without menu

### ISSUE THREAD

**Issue by sdurnov** [telerik/kendo-themes#89] opened 2018-03-27 19:01 UTC
Columns without menu has vertically centered content, but text in column header with filtering menu misaligned. Exists in your plunker from filtering documentation page. Compare ID column header text alignment with other columns.

https://www.telerik.com/kendo-angular-ui/components/grid/data-operations/filtering/#

**Comment by gyoshev** [comment] 2018-08-22 14:53
I could not reproduce this with the latest versions in neither Firefox nor Chrome, and the issue sounds like a duplicate of https://github.com/telerik/kendo-theme-default/issues/834, so I'll assume that it has been fixed with the same patch.

**Closed by gyoshev** 2018-08-22 14:53 UTC
Labels: C:Grid, bug
