### ISSUE TITLE
material 2.5.2 and bootstrap 3.4.2 breaks angular grid no record text display

### ISSUE THREAD

**Issue by DanielHTpg** [telerik/kendo-themes#779] opened 2019-06-12 17:09 UTC
## I'm submitting a...

* Regression report 

## Current behavior

The new versions of the bootstrap and material package break the no records template text display. The applied `k-grid-norecords` class causes the no records `td` element to only display in the first gird column instead of stretching over all columns.
![image](https://user-images.githubusercontent.com/24475714/59371588-b9254c80-8d45-11e9-8fc0-064ae8f46e43.png)

## Expected behavior

No records template stretches properly over all columns.

## Minimal reproduction of the problem with instructions

I used the https://www.telerik.com/kendo-angular-ui/components/grid/api/NoRecordsTemplateDirective stack blitz as my example base.

Bootstrap version showing the bug:
https://stackblitz.com/edit/angular-gkaabq

Material version showing the bug:
https://stackblitz.com/edit/angular-lus2fe

The default theme is not affected which is visible when opening the kendo example in stackblitz.

## Environment
Product:
* Kendo Ui for Angular

Package versions:

```
"@progress/kendo-theme-material": "2.5.2"
or 
"@progress/kendo-theme-bootstrap": "3.4.2"
```

Browser:

- Chrome (desktop) 74.0.3729.169

System:
- Platform:  Windows

**Comment by joneff** [comment] 2019-06-14 08:39
Duplicate of #783.

Note: we already fixed the issue and it will shortly be available in the dev channel.

**Closed by joneff** 2019-06-14 08:39 UTC
Labels: bug, duplicate
