### ISSUE TITLE
"No records available." is incorrectly positioned

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#783] opened 2019-06-13 11:32 UTC
## I'm submitting a...
* Bug report 

## Current behavior
The "No records available." is positioned only in the first column of the Grid.

## Minimal reproduction of the problem with instructions
Check the following example:
[https://stackblitz.com/edit/angular-z9nu9d-fu8jwh?file=app/app.component.ts](https://stackblitz.com/edit/angular-z9nu9d-fu8jwh?file=app/app.component.ts)

## Environment
Product:

* Kendo Ui for Angular

**Comment by danielkaradachki** [comment] 2019-06-13 11:43
duplicate of https://github.com/telerik/kendo-themes/issues/781

**Closed by danielkaradachki** 2019-06-13 11:43 UTC
Labels: C:Grid, T:Bootstrap, T:Default, T:Material, bug, duplicate
