### ISSUE TITLE
Extract all variables for the Grid component

### ISSUE THREAD

**Issue by silviyaboteva** [telerik/kendo-themes#1027] opened 2019-10-29 14:14 UTC
**Is your feature request related to a problem? Please describe.**
Extract all variables for the Grid component, that are including appearances and depending on other styles.

**Describe the solution you would like to see implemented**
Extract those variables from the theme files and remove the appearance mixins. This refactoring must **not** regress the current design and behavior.

**Additional context**
We can achieve decoupled styles and more flexibility when customizing the styles for a given component. This enhancement will be needed for creating a consistent and flexible styleguide for creating forms with Kendo components.

Related to: https://github.com/telerik/k2/issues/150

**Comment by silviyaboteva** [comment] 2019-11-14 12:49
After a discussion with @elena-gancheva, we need to freeze this refactoring for now (also related to Scheduler and Editor components). So, I'll remove it from the project's To Do for now.

**Comment by PreslavKozovski** [comment] 2020-02-26 16:47
duplicate of https://github.com/telerik/kendo-themes/issues/211

**Closed by PreslavKozovski** 2020-02-26 16:47 UTC
Labels: C:Grid, Enhancement, FW:Angular, FW:React, SEV:High, T:Bootstrap, T:Default, T:Material, duplicate
