### ISSUE TITLE
Custom swatch doesn't compile: Undefined variable: "$input-bg"

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1996] opened 2020-10-20 09:13 UTC
**Describe the bug**
Using the following swatch:

```
// Variables.
$primary: blue; 
$secondary: pink; 

// Import the theme file for the components you use. 
@import "../grid/_index.scss";
```

and running the **npm run sass:swatches** command throws an error: _Error: Undefined variable: "$input-bg"_.

The error can be further reproduced by following the steps at the following article:
https://www.telerik.com/kendo-react-ui/components/styling/customizing/#customizing-themes-with-swatches

**Comment by joneff** [comment] 2020-11-04 16:24
Duplicate of #1973. Please refer to it and the related PR.

**Closed** 2020-11-04 16:25 UTC
Labels: T:Bootstrap, T:Default, bug, duplicate
