### ISSUE TITLE
Nested imports in version 7.0.2 of the themes throws The module "A" depends on module "B", but the styles have not been loaded yet

### ISSUE THREAD

**Issue by filipKovachev** [telerik/kendo-themes#4902] opened 2024-02-23 11:48 UTC
**Describe the bug**
When using version 7.0.2 version of the themes multiple The module "A" depends on module "B", but the styles have not been loaded yet warnings are thrown when using a nested import. This is not observed in version 6.0.3 for example. This is due to the module system.

**To reproduce**
1. Download the initially send sample project from ticket 1635965
2. Run npm install and npm run start
3. Observe the multiple warnings that are thrown

**Expected behavior**
When using nested imports these warnings should not be thrown

Reported in Ticket ID: 1635965

**Comment by epetrow** [comment] 2024-06-05 14:44
Closing this as duplicate of [2286](https://github.com/telerik/kendo-themes/issues/2286)

**Closed by epetrow** 2024-06-05 14:44 UTC
Labels: Bug
