### ISSUE TITLE
Grid header border misalignment on horizontal scrolling

### ISSUE THREAD

**Issue by yanmariomenev** [telerik/kendo-themes#4107] opened 2022-11-18 09:37 UTC
**Describe the bug**
When the Grid horizontal scroll is at the end, the header borders are misaligned.

**To reproduce**

1. Go to https://stackblitz.com/edit/angular-tozhus?file=src%2Fapp%2Fapp.component.ts
1. Move the horizontal scroll to the end of the Grid

React example - https://www.telerik.com/kendo-react-ui/components/grid/scroll-modes/#toc-infinite-scrolling
Vue example - https://www.telerik.com/kendo-vue-ui/components/grid/scroll-modes/#toc-infinite-scrolling

**Screenshots**
![chrome_RlYh5IIzLS](https://user-images.githubusercontent.com/49076727/202668198-0e50b436-c811-4cb4-924c-88c203552207.png)
![chrome_ujTxdE5nJt](https://user-images.githubusercontent.com/49076727/202668349-3b34ff05-4a0a-40b9-95c9-455f7c9a4c64.gif)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue

**Affected browsers (please remove the unneeded items)**
* Chrome version: [latest]

**Build system information (please remove the unneeded items)**
* OS: [Windows 11]

**Additional context**
The issue doesn't seem present in Mac and Firefox browsers.

**Comment by joneff** [comment] 2022-11-28 17:31
By any chance, are you using a zoomed browser?

**Comment by yanmariomenev** [comment] 2022-11-29 09:21
Browser zoom is set to 100%, but it seems that the recommended Windows scale of 125% is the culprit. Setting the scale to 100% doesn't misalign the columns.

**Comment by joneff** [comment] 2022-11-29 11:31
If that's the case, then the issue is related to JS, not CSS. Closing as invalid.

**Closed by joneff** 2022-11-29 11:31 UTC
Labels: invalid, C:Grid, FW:Angular, FW:React, FW:Vue
