### ISSUE TITLE
SCSS compile error Undefined variable: "$button-border" 

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#1974] opened 2020-10-14 11:56 UTC
**Describe the bug**
Using the latest Kendo Default theme 4.24.0 version and compiling the project then the following error is thrown:

> Undefined variable: "$button-border" 
> 
> \@progress\kendo-theme-default\scss\input\_variables.scss (line 42, column 16)

**Affected package**
* theme-default

**Affected suites**
* Kendo UI for Angular

**Affected browsers**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment] 2020-11-04 16:24
Duplicate of #1973. Please refer to it and the related PR.

**Closed by joneff** 2020-11-04 16:24 UTC
Labels: T:Default, bug, duplicate
