### ISSUE TITLE
Grid PDF export with auto paperSize exports only the first page n-times

### ISSUE THREAD

**Issue by Alex-Bubblemaster** [telerik/kendo-themes#18] opened 2018-02-14 14:04 UTC
### Bug report

Reported in ticket with ID 1133858 

### Reproduction of the Problem

- `pdf.allPages: true`
- `paperSize: "auto"`

[Dojo](http://dojo.telerik.com/@bubblemaster/OBUDox/2) with an old theme exports all pages correctly

[Dojo](https://dojo.telerik.com/@bubblemaster/uSIYoh/2) with a SASS theme exports only the first page, disregards both the `template` and the `scale`

### Environment

Kendo version 2018.1.117

**Comment by TsvetinaIvanova** [comment] 2018-11-15 10:08
Also reported in 1356998. 
An additional issue (probably a side effect) is that the loading overlay and progress bar are visible in the exported document.

**Comment by PreslavKozovski** [comment] 2019-01-16 09:59
duplicate of https://github.com/telerik/kendo-ui-core/issues/4291

**Closed by PreslavKozovski** 2019-01-16 09:59 UTC
Labels: Enhancement, SEV:High
