### ISSUE TITLE
Use of ~ in scss imports is deprecated 

### ISSUE THREAD

**Issue by goat67** [telerik/kendo-themes#4203] opened 2023-01-06 17:17 UTC
**Describe the bug**
Warning: 'C:\repos\Ag-Portal-UI\node_modules\@progress\kendo-theme-material\scss\action-buttons\_layout.scss' imports '~@progress/kendo-theme-default/scss/action-buttons/_layout.scss' with a tilde. Usage of '~' in imports is deprecated.

**To reproduce**
Include @progress\kendo-theme-material in an angular project and compile

**Expected behavior**
No Error Message received.

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for Angular

**Affected browsers (please remove the unneeded items)**
* Not Applicable

**Build system information (please remove the unneeded items)**
Angular version 14

Angular 15 no longer will compile if a tilde is used

[https://stackoverflow.com/questions/74717514/sasserror-cant-find-stylesheet-to-import-getting-error-while-taking-the-buil](https://stackoverflow.com/questions/74717514/sasserror-cant-find-stylesheet-to-import-getting-error-while-taking-the-buil)

**Comment by TeyaVes** [comment] 2023-01-09 12:06
duplicate of: https://github.com/telerik/kendo-themes/issues/3963

**Closed by TeyaVes** 2023-01-09 12:06 UTC
Labels: bug
